### ISSUE TITLE
Magnitude required to PoBH mine

### ISSUE THREAD

**Issue by 616westwarmoth** [biblepay/biblepay#20]
Perhaps we should use magnitude based on the "Magnitude (One-Week)" instead of "Magnitude (One-Day)".  This shouldn't adversely affect the integrity of the system and would avoid any issues that could come up if the projects ran out of tasks (unlikely now that there is a backup) or the PoDC Superblock was corrupted (as has occurred)

**Comment by sunk818** [comment]
I'd want Mag One Day first. If the value for One Day is 0, check Mag One week as a fall back to see if there is a value greater than 0 there. If there is, then use that as the value.

**Comment by thesnat21** [comment]
I like the idea...
This would have to be a network-wide update to be accepted, so must go into a mandatory assuming @biblepay  agrees

**Comment by biblepay** [comment]
Taking a look at this idea, I agree it would be a good feature to help us transition over any day where we might hit a pothole (like those days when superblocks arent paid) despite the fact we are eliminating those, it would be good for researchers to continue to heat mine  (and be good for network security), if they experience a lapse of one day.

Part of the problem is the calculation time required to determine if one has been paid, as the weekly magnitude feature is cosmetic, calculated internally and only calculated for your CPID (not for everyone).

However, I think we can accomplish this same rule by saying Has the CPID successfully staked any UTXO in the last 7 days.  Since the UTXO is signed by the CPID, and known by all nodes, I think this will work.

So yes, I will propose that we change 'CPID with magnitude' over to 'CPID that has staked a UTXO within 7 days'. 

Ill go ahead and look into adding this to our current testnet phase now.

**Comment by biblepay** [comment]
Alright I will merge this into testnet for testing...
