### ISSUE TITLE
Sanctuaries receiving back-to-back rewards

### ISSUE THREAD

**Issue by 616westwarmoth** [biblepay/biblepay#22]
Sanctuaries still occasionally receive back-to-back rewards.  The last one I saw was 44966 and 44967 which were both received by MN BMzQQ29EcQyNanxpi1afjLYaxwx5exsfQJ.

This skews the expected rate of return for Sanctuaries as the back-to-back rewards are sporadic and unpredictable.  But this goes against the Economics page which states "38.5% is given to the longest waiting Sanctuary".

**Comment by biblepay** [comment]
"This skews the expected rate of return for Sanctuaries as the back-to-back rewards are sporadic and unpredictable. But this goes against the Economics page which states "38.5% is given to the longest waiting Sanctuary".

I disagree- the 38.5% bears itself out over time, just as fluctuating difficulties equalize the block time over time.

"Sanctuaries still occasionally receive back-to-back rewards. The last one I saw was 44966 and 44967 which were both received by MN BMzQQ29EcQyNanxpi1afjLYaxwx5exsfQJ."

Yes, that is by design.  The rewards are based on the queue position, not that sancs have not been paid.
