### ISSUE TITLE
Feature Request: Wallet UI - Add Erasechain Menu Option

### ISSUE THREAD

**Issue by togoshigekata** [biblepay/biblepay#36]
User Story: As a regular user of BiblePay, I want to be able to easily get on latest chain when my wallet chain doesnt match my peers 

Currently users can add -erasechain=1 to desktop shortcut or add erasechain=1 to biblepay.conf, but I believe this a little bit technical for the average person (and grandma)

Tools >> Wallet Repair >> Erasechain?
https://github.com/biblepay/biblepay/blob/master/src/qt/bitcoingui.cpp#L505
https://github.com/biblepay/biblepay/blob/master/src/qt/rpcconsole.cpp#L457
https://github.com/biblepay/biblepay/blob/master/src/qt/rpcconsole.h#L94
https://github.com/biblepay/biblepay/blob/master/src/qt/forms/debugwindow.ui#L1474

What is Erasechain?
https://whitewalr.us/2019/biblepay-erasechain-not-reindex.html

Or maybe replace rebuild index with erasechain?

**Comment by biblepay** [comment]
I like Suns whitewalrus post about this; its pretty positive over all except I see out of two comments an actual negative comment from someone who didnt even bother to see we can sync our chain in 10 minutes still (once you get up to 8 connections), since we only have 210K blocks.

Anyway, erasechain was made when I noticed that DASH stores way more data than bitcoin in the extra index files.  Think of LLMQ, EvoDB, masternodecache, etc.  So if the node ever goes off the main chain and stores some of that data, its best to get rid of it when resyncing so there is no chance of using it to break the consensus, etc.

Yes, this is a cool suggestion, thanks.

Although in general, I hope we don't need to use it, but this would be a great addition to our GUI tools page.

And eventually yes we will definitely have a snapshot sync option alternative - coming soon.

**Comment by biblepay** [comment]
I added an erasechain GUI option to harvest.
