### ISSUE TITLE
1.1.5.9 biblepaycore32.exe Chrome 69 and Windows 10 flags as virus

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#46]
When I tried to download the biblepaycore32.exe file, Chrome (Version 69.0.3497.100 (Official Build) (64-bit)) refused saying it was a virus.

I used wget to download it.

Windows 10 64-bit antivirus flagged it as a virus

Used sha256 from here: http://www.sedosoft.com/downloads/crypto/SHA256/
```
C:\temp>sha256 biblepaycore32.exe
Copyright (c) 2009,   sedosoft, inc.,   All Rights Reserved.
SHA256 v3   http://www.sedosoft.com/downloads/crypto/SHA256/

biblepaycore32.exe:8285ba23185e523f28882c8eaa3bd66debe985aceeb38242cd2fce1345e7953f
```

![fs20181013-52](https://user-images.githubusercontent.com/6989799/46909065-5beca900-cee1-11e8-8ac1-ffba490d574e.jpg)

**Comment by thesnat21** [comment]
Unfortunately this is due to a paranoid AV...  Not too much we can do about it at this point.

**Comment by biblepay** [comment]
Since virustotal.com does not flag our 32 bit as a virus, this points to a false positive in Windows Defender.  I recommend contacting windows defender with our hash and asking them to whitelist it.

We don't have any mining program embedded in BiblepayCore that should trigger a virus - ours is 100% native code - (in contrast to the cgminer.exe problem, where that is a known program to trigger a virus false positive).

**Comment by sunk818** [comment]
I was able to submit the biblepaycore32.exe that throwing off the false positive:

https://www.microsoft.com/en-us/wdsi/submission/c25846e2-2f59-47ea-9f4d-e910aadbd996
