### ISSUE TITLE
Need to add the POW Difficulty to the "getdifficulty" command

### ISSUE THREAD

**Issue by thesnat21** [biblepay/biblepay#53]
And also make it more clear which is which.

**Comment by biblepay** [comment]
The problem with this idea is some external third party RPC calls rely on 'getdifficulty'.  The RPC calls are fragile because when they result in a single variables output (like getdifficulty just returns a double), that means things like exchanges and block explorers will be expecting it.  (I made getdifficulty return PODC diff because we are primarily podc, I suppose it could have been POBH diff, but at the time I made that call).

For now you can get both difficulties by calling getmininginfo - both are labeled.

We could add a parameter to 'getdifficulty' such as 'pow' and 'podc' and have it return specific things also or make a dedicated command such as getpobhdifficulty that returns both or one or whatever.

**Comment by thesnat21** [comment]
Fair enough,  PODC diff changes so slowly :)

I'm not sure why but most dash 12.3 tools seem to fail against our tools.   Thanks for the background

**Comment by sunk818** [comment]
Podc doesn't secure the block chain. Getdifficulty should display pow difficulty value

**Comment by biblepay** [comment]
I figure I owe this to the thread:
Let me put you in my line of thinking for a minute.  When PODC was being developed, I actually thought it would attract at least one new researcher per day and give us 2000 or so.  And with the cheap reward in POW, I figured our pow diff would be unnaturally low most of the time (which is generally the case now that we went to podc).

If our PODC diff was generally around 30,000 and POW diff at 2000, which one would be representative of biblepay when you look at us from aggregate sites - POBH - thats because that is where our money is being spent.

Its still technically true that POBH represents the diff level of biblepay - because we spend the majority of our mining rewards there.

So please realize Im not being difficulty (pardon the pun).

**Comment by thesnat21** [comment]
Thanks for the clarification!  I agree that helps it make more sense.

And who doesn't like a good pun?

**Comment by sunk818** [comment]
I see that PoG difficulty will be the new `getdifficulty`. I'm still of the opinion `getdifficulty` should reflect whatever secures the blockchain... in this case PoW (or PoBH). If PoG ever replaces PoBH, then it makes sense to use PoG difficulty value. It seems gimmicky to use a difficulty value that has no context in other algorithms, while PoW difficulty from X11 is more comprehensible. To have a low difficulty actually attracts miner because they understand there's a better chance of mining rewards instead of a high difficulty value.

**Comment by biblepay** [comment]
No we are not gimmicky -  I believe we should always have *all* of the difficulty levels equally available, clearly, in getmininginfo (like we do).  We have pog_difficulty, pow_difficulty, podc_difficulty.

Whether PODC is retired or POG is active, that is still the case; they are all listed.

The only sticky point here is which algorithm is reported when someone typed 'getdifficulty'.  The argument is either the one that pays the most rewards per day, or the one that secures the blockchain the most. (Neither of those things are gimmicky).

I agree that the block security algo should be returned in getdifficulty.  Its currently coded that way.

After we transition to POG, you will still see the POBH diff in getdifficulty.
