### ISSUE TITLE
Black console window pop-ups when launched on windows.

### ISSUE THREAD

**Issue by thesnat21** [biblepay/biblepay#55]
Please hide the black console windows.

**Comment by biblepay** [comment]
I took a look at this problem, and unfortunately it requires a newer version of boost to fix it (MIP already imported the version for the mac build).  However I am reluctant to use the call until we re-base to evolution, because it could break our current exchange build process.

Its safer for us to fix this in the rebase and require the exchanges to build off of the new branch as an atomic change.

Ill leave this open MIP.

**Comment by MIPPL** [comment]
The only way to go in Windows is replacing the popen call with the Win32 CreateProcess call, and the absurdly convoluted windows pipes in order to read output.

**Comment by MIPPL** [comment]
Solved
