### ISSUE TITLE
Let Proposals List show current proposals by default

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#58]
I'd like to suggest Proposals only show pending proposals by default. Past proposals should be grouped by the monthly superblock they are a part of.

At the bottom of the Proposals view, have navigation that takes you to previous monthly superblock. So, if December 2018 are the pending proposals, show this by default. There would be a button on the lower left part that takes you to last month's superblock (or whatever block height it was). If you go to that superblock, then you have two buttons (left button takes to Oct superblock) and right button takes you to Dec pending superblock. User should be able to click left all the way to the first monthly superblock.

You can take ideas from Dash Ninja for display of governance objects: https://www.dashninja.pl/governance.html

**Comment by biblepay** [comment]
Since we only have 10 proposals per month that can fit on one screen I fail to see the benefit of all this.

Dashninja is a web site.  I can see the benefit in adding an archived proposal view to pool.biblepay.org (since it is essentially doing what dashninja does now).

Anyway, this can be prioritized at a 1 unless someone wants to pick it up for the core wallet.  Alternatively one can enhance biblepay-central to include dashninja's logic as another option.

Or enhance pool.biblepay.org.

**Comment by thesnat21** [comment]
I'm working on a site that will manage this view.

I agree the GUI should be limited to active proposals for the current cycle,  less noise and history is not as relevent in the GUI.

**Comment by biblepay** [comment]
Once we get to the point where we have a cadillac, we could come back and add these nice to have things to the core - for example have an archived proposals view that has nav buttons, but again, its a low priority compared to the huge benefits we reap with adhering to the roadmap.  (The roadmap has some things for IPFS coming up - like voting on objects, and of course our dash rebase - and writing letters within the wallet - etc).

**Comment by sunk818** [comment]
https://forum.biblepay.org/cc/governance

Someone made a web site with masternode data so that will do for now.
