### ISSUE TITLE
titheinfo highest ROI is showing negative number

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#68]
Perhaps it is due to PoG difficulty value being above 65536, but highest ROI (last metric) on `titheinfo` is showing as a negative number.

```
10:39:08 |   | titheinfo
10:39:08 |   | {   "24_hour_tithes": 128902.4,
   "pog_difficulty": 166639.1616298037,
   "min_coin_age": 60,
   "min_coin_amt": 25000,
   "max_tithe_amount": 1,
   "Tithable_Coin_Quantity": 0,
   "Tithable_Largest_Coin": 0,
   "Tithable_Coin_Avg_Age": 0,
   "Tithable_Total_Coin_Balance": 0,
   "Tithability_Amount": 0,
   "Tithability_Summary": "NO",
   "Tithe_Cap": 50694,
   "Daily_Miner_Emissions": 94628,
   "Pool_Emissions": 75702.40000000001,
   "Lowest_ROI%": 16.5,
   "Highest_ROI%": -35 }
```

**Comment by biblepay** [comment]
This is correct, at that particular time - since the pool inducted more than the extrapolated daily tithe cap over the last 40 blocks with legal tithes..  Im discussing some potential small tweaks with MIP now that I think will permanently solve that - maybe we can propose these in tandem with retiring PODC.  One is decreasing the max tithe to 3 bbp or so.  The other is requiring 1 day of coin age at diff 0.  If we did these two things the ROI should always be stable and run ups over short-term block counts wont cause the ROI to change much.

**Comment by sunk818** [comment]
> One is decreasing the max tithe to 3 bbp or so.

We are going from 300 BBP to 3 BBP? Seems a bit aggressive.

**Comment by biblepay** [comment]
I think 3 bbp would mean lower avg diff and more frequent tithes, but would allow up to 20,000 concurrent new users in the pool per day.  30 would work also, but I dont think 3 hurts anyone (it just increases tithe frequency).

**Comment by sunk818** [comment]
When I type `titheinfo`, I'm seeing Lowest_ROI% as -184.5
