### ISSUE TITLE
Unable to tithe

### ISSUE THREAD

**Issue by MIPPL** [biblepay/biblepay#77]
Sakik in Discord reported:

> why I am not able to tithe? version 1.1.8.9
> biblepay-cli titheinfo
> {
>   "24_hour_tithes": 6086.8988562,
>   "pog_difficulty": 7868.866074817685,
>   "min_coin_age": 7.42,
>   "min_coin_amt": 3002.66,
>   "max_tithe_amount": 8.83,
> 
> biblepay-cli exec getdimensionalbalance 0 0
> {
>   "Command": "getdimensionalbalance",
>   "Amount 205.00": "Age 7.83",
>   "Amount 1326.00": "Age 1.05",
>   "Amount 200.00": "Age 11.57",
>   "Amount 353.00": "Age 3.81",
>   "Amount 22036.00": "Age 12.01",
>   "Amount 205.00": "Age 7.83",
> 
> biblepay-cli tithe 8
> {
>   "Error": "Unable to Create Transaction: Unable to locate coins older than minimum_tithe_coin_age."
> }

**Comment by sunk818** [comment]
Some are speculating that the amounts are grouped together, but the individual coin balances may not meet the min coin amount requirement. Is there a better way to diagnose or command to run to check?

**Comment by biblepay** [comment]
Please try this first;  from the looks of his report he has coin-age.
I remember in testnet, someone did -zapwallettxes=2 and it timestamped the tx's wrong.

Could you please try restarting the wallet with -rescan and then see if this tx creates?

Let us know, as that would confirm the individual wallet has bad timestamps.

One other option is to go to your wallet backups folder and bring in an old wallet and restart (but do make sure you dont lose *any* coins).

**Comment by sunk818** [comment]
@biblepay you stated `exec getdimensionalbalance 0 0` brings back all coin balances, so it sounds like they are not grouped together. If a balance belongs to PoDC or PrivateSend, are they ineligible to tithe?

**Comment by biblepay** [comment]
@Sunk818, We actually don't have any balances belonging to PODC, we just have PS-Denoms and POG-Denoms (no podc-denoms).  

They should be eligibile to tithe PS-Denoms and POG-Denoms and non-pog-denoms (except locked funds or locked Sanc funds).

**Comment by capulo** [comment]
getdimensional balance swhowing sum of same age, i had 400k splitted to many piles but in report it was as 400k. so i'm 99.99% sure that sakik just dont have pile with needed attributes

**Comment by sunk818** [comment]
The 4k error was due to 2k x 2. Can not tithe 2k because min coin value was 4k. Most likely due to `exec bankroll` . It creates same transaction amount at same time and value. Then those balances are grouped and summed together.

I have data to backup but can't send right now.

**Comment by biblepay** [comment]
Ok, we are getting somewhere thanks guys, but let me try to understand this a little better.

Does it mean we need to enhance the code to give a more verbose getdimensionalcoins report only, or does it mean biblepay won't tithe individual transaction outputs from the POG bankroll coins?

Another words , do we have an emergency that I need to fix to get it to tithe individual pieces of Pog txs?

**Comment by capulo** [comment]
in my case its just about output style, i have 50x 10k coins in wallet and getdimensionalbalance is showing them as 500k, 7 days age - so summed

**Comment by sunk818** [comment]
@biblepay , @capulo is right. 

If it takes the results from `exec getdimensionalbalance` based min coin age and min coin value... then would showing each coin balance individually be the best way forward?

Other areas of wallet to review:
1) Tithe Ability - how is "Tithe Ability" value determined?
2) titheinfo - the output on that command will need review
3) anything @MIPPL did with PoG Engine Room

Following is from @vahtis:

![image](https://user-images.githubusercontent.com/6989799/53141632-ab08b180-3545-11e9-9f2e-b616c1fb8c33.png)

```css
18:50:21 exec getdimensionalbalance 7 3000
18:50:21 {
  "Command": "getdimensionalbalance",
  "Amount 4000.00": "Age 13.93",
  "Total": 4000
}
```

Send, Coin Control Inputs show 2 x 2000.001 BBP from `exec bankroll` made on 2 Feb 2019 (~14 days ago)

![image](https://user-images.githubusercontent.com/6989799/53141693-e905d580-3545-11e9-9131-ff46f1b45099.png)

from debug.log:

```css
BiblePayMiner::SendTithe::Error - Unable to send tithe - Amount 7.200000, Error Unable to Create Transaction: Unable to locate coins older than minimum_tithe_coin_age.  

Created Tx for Outbound Money 800000000.000000 to address BB2BwSbDCqCqNsfc7FgWFJn4sRgnUt4tsM

Creating Tx Message <TITHER>xxx</TITHER><NICKNAME>xxx</NICKNAME><TITHESIGNER>xxx</TITHESIGNER><PACK><MT>MESSAGE</MT><MK>OUT_TX</MK><MV> </MV></PACK>  

CreateTransaction::Requiring specific coin age 9.710000 and coin amount 3958 
```

```css
18:57:51 titheinfo
18:57:51 {
  "24_hour_tithes": 8024.9115364,
  "pog_difficulty": 10374.24074787619,
  "min_coin_age": 9.710000000000001,
  "min_coin_amt": 3958.36,
  "max_tithe_amount": 8.460000000000001,
  "Tithable_Coin_Quantity": 1,
  "Tithable_Largest_Coin": 4000.002,
  "Tithable_Coin_Avg_Age": 13.93104166666667,
  "Tithable_Total_Coin_Balance": 4000.002,
  "Tithability_Amount": 8.460000000000001,
  "Tithability_Summary": "YES",
  "Tithe_Cap": 50694,
  "Daily_Miner_Emissions": 94628,
  "Pool_Emissions": 75702.40000000001,
  "Lowest_ROI%": 16.5,
  "Highest_ROI%": 44.5
}
```

```css
18:58:06 exec getdimensionalbalance 0 0
18:58:06 {
  "Command": "getdimensionalbalance",
...
  "Amount 4000.00": "Age 13.93",
...
  "Total": xxx
}
```
relevant txes from listunspent:

```css
18:56:39 listunspent 
18:56:39
[
    {
    "txid": "b962649008ef25c319f8c2f3c99646a20145d1e4dd860079e78b989981c34413",
    "vout": 0,
    "address": "xxx",
    "account": "TITHES",
    "scriptPubKey": "xxx",
    "amount": 2000.00100000,
    "confirmations": 2761,
    "ps_rounds": -2,
    "spendable": true
  }, 
  {
    "txid": "b962649008ef25c319f8c2f3c99646a20145d1e4dd860079e78b989981c34413",
    "vout": 7,
    "address": "xxx",
    "account": "TITHES",
    "scriptPubKey": "xxx",
    "amount": 2000.00100000,
    "confirmations": 2761,
    "ps_rounds": -2,
    "spendable": true
  }, 
```

**Comment by biblepay** [comment]
So it appears the wallet is able to successfully pick an individual aged output out of a bankroll transaction and tithe that (without disrupting the rest of the outputs), and, it does find the output in SelectCoinsForTithing (in auto tithe mode) or in manual mode, so that part is OK, but I do see a few small tweaks we need based on this issue.

1)  I modified getdimensionalcoins to be more verbose - and show every single tithing coin - one per row.
2) The auto-tithe feature was only tithing 90%.  Fixed to tithe 100%.
3) Adjusted the Send Coins Entry UI to refresh once per minute, so if blocks click by, it will update
4) Modified sendcoins UI display values to show the entire scale (they were rounded down).

As far as what are the rules for tithability, see the "titheinfo" rpc command.  If you still have questions after seeing the code (its pretty straight forward, tithability means your coin met the difficulty parameter) then please ask a more specific question.

This leisure should be out by tonight / tomorrow morning.

**Comment by sunk818** [comment]
@biblepay said 
> As far as what are the rules for tithability,
re: > 1. How is "Tithe Ability" value determined?

I didn't mean for you to explain the algorithm, just asking if fixing `titheinfo` output will fix the potential issues I asked about. 

If `titheinfo` will show "every single tithing coin", then I'm assuming Tithe Ability will say Qty: 0 because `titheinfo` will show 2000 BBP two times, rather than 4000 BBP one time.

**Comment by biblepay** [comment]
@sunk818 Yes, since getdimensional is more verbose now, it actually will affect the titheinfo responses, yes definitely, however what Im still confused about is if he had a 4000 coin with the same age as the 2*2000 coins (as the pack ages together) than the tithabilility you refer to should have already been "Yes", so there is a discrepency somewhere here in supplied test data.

**Comment by vahtis** [comment]
There was no 4000 coin there were only 2*2000 coins.
I was not able to tithe from wallet! 
In titheinfo "Tithability_Summary": "YES", should have been NO
There is no discrepency in test data

**Comment by sunk818** [comment]
@biblepay at the time, min coin value with 3958. so, having 2x2000 BBP means 2000 is less than the require 3958. 
@vahtis Under the same conditions, you should see `Summary: No` now. Please let us know if this is the case now. I can verify that `exec getdimensionalbalance 0 0` is verbose and correctly displays the individual coin balance values.

**Comment by vahtis** [comment]
Latest version corrects this bug

**Comment by biblepay** [comment]
Ok I understand.
