### ISSUE TITLE
enhance: auto tithe picks optimal balance with least min coin age and least min coin value to tithe

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#84]
I'd like to request an auto tithe where the least min coin age and least min coin value input is used when auto tithing. 

https://viisastentori.fi/bbp_test/index.php has a tool gives some visibility to how much coin you need to participate on any given block. Seems like 5k-6k BBP would let you participate often. 9k-10k if you always wanted to participate... assuming you had enough min coin age.  Now, we also have to see how auto tithe works and better it chooses coins optimally or randomly. If you have a 10k BBP balance, but 5k BBP would work just as well, would 10k BBP would be picked in some instances of auto-tithe?

**Comment by biblepay** [comment]
Yeah, this sounds like a good idea that we need relatively quick, as I can see people getting upset they did a lot of work to age the coins and then we spend them in the wrong order as soon as difficulty drops...

So, I think the best way to do this, since POG requires one coin to be spent at a time, is to give exec getdimensionalbalance the ability to pick one coin (IE the one that is the least coin age and least amount - for a given difficulty level) and return it as "best coin", this way when we call selectcoinsforstaking, we will also have the "best coin" txid-vout available.  Then when we tithe, we can pass in the "suggested coin" into the tithe.  Then when we spend our balance, the wallet will only spend the 'txid-vout' identified coin in the transaction.

Another words, the wallet will always tithe the coin with the least coin age and least amount for a given diff level.

**Comment by biblepay** [comment]
After testing it prod it appears this is working.

**Comment by sunk818** [comment]
Feature in 1196: https://github.com/biblepay/biblepay/commit/6d4a30742281fed1b513a00299009bf39c039cc9

Activated in 1198: https://github.com/biblepay/biblepay/commit/eae263d6c6ac16f0bfb3100f994d040918c90f68
